### ISSUE TITLE
`jamf_api_tool.py` Errors 

### ISSUE THREAD

**Issue by dan-snelson** [grahampugh/jamf-upload#39]
On a fresh install of …
- macOS 11.6.1 (20G224) on Intel
- git 2.30.1 (Apple Git-130)
- autopkg 2.3.1

… with a local clone of [jamf-upload](https://github.com/grahampugh/jamf-upload), I’m observing the following errors:

``` console
% /usr/local/autopkg/python ~/Documents/GitHub/grahampugh/jamf-upload/jamf_api_tool.py --prefs ~/Library/Preferences/com.github.autopkg.plist --computers --all --verbose

** Jamf API Tool for Jamf Pro.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   379    0   379    0     0   2005      0 --:--:-- --:--:-- --:--:--  2005
Session token received
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   424  100   424    0     0   2409      0 --:--:-- --:--:-- --:--:--  2409
Traceback (most recent call last):
  File "/Users/ladmin/Documents/GitHub/grahampugh/jamf-upload/jamf_api_tool.py", line 1060, in <module>
    main()
  File "/Users/ladmin/Documents/GitHub/grahampugh/jamf-upload/jamf_api_tool.py", line 1026, in main
    handle_computers(jamf_url, enc_creds, args, slack_webhook, verbosity)
  File "/Users/ladmin/Documents/GitHub/grahampugh/jamf-upload/jamf_api_tool.py", line 52, in handle_computers
    for x in obj:
TypeError: 'NoneType' object is not iterable
```

**Comment by 0bl1t3r4t3** [comment]
Any updates on this?

**Comment by grahampugh** [comment]
jamf-api-tool was moved to its own repo, grahampugh/jamf-api-tool.

I've no idea if this is still an issue, but if so, please re-raise over there! Thanks!
