### ISSUE TITLE
WARNING: Could not read HTTP response. The package was probably not uploaded successfully

### ISSUE THREAD

**Issue by at-danderson** [grahampugh/jamf-upload#57]
I apologize if this is the wrong place to put this, but I have not been able to find any other sources of assistance.

Trying to use JamfPackageUploader and getting this:
```
WARNING: Could not read HTTP response. The package was probably not uploaded successfully
```

Attempting to migrate from JSSImporter.  Using the same API_USERNAME, API_PASSWORD, and JSS_URL that was working successfully on JSSImporter.

This is the command I am trying:
```
autopkg run visualstudiocode.pkg --post com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
```

It doesn't seem to matter what I put in for the API_USERNAME or API_PASSWORD (I've tried valid users/passwords and invalid ones to attempt to get a different error) but the result is always the same.

I have also set up the JAMF user as directed, but gave it full admin rights to see if that would change anything but it did not.

Output from the JamfPackageUploader portion of the -vvv output below:

```
com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
{'Input': {'API_PASSWORD': 'password',
           'API_USERNAME': 'username',
           'JSS_URL': 'https://mydomain.jamfcloud.com:8443',
           'pkg_path': '/Users/autopkg/Library/AutoPkg/Cache/local.pkg.visualstudiocode/Visual '
                       'Studio Code-1.65.2.pkg',
           'version': '1.65.2'}}
JamfPackageUploader: No value supplied for pkg_name, setting default value of:
JamfPackageUploader: No value supplied for pkg_category, setting default value of:
JamfPackageUploader: No value supplied for pkg_info, setting default value of:
JamfPackageUploader: No value supplied for pkg_notes, setting default value of:
JamfPackageUploader: No value supplied for pkg_priority, setting default value of: 10
JamfPackageUploader: No value supplied for reboot_required, setting default value of:
JamfPackageUploader: No value supplied for os_requirements, setting default value of:
JamfPackageUploader: No value supplied for required_processor, setting default value of: None
JamfPackageUploader: No value supplied for send_notification, setting default value of:
JamfPackageUploader: No value supplied for replace_pkg, setting default value of: False
JamfPackageUploader: No value supplied for replace_pkg_metadata, setting default value of: False
JamfPackageUploader: No value supplied for SMB_URL, setting default value of:
JamfPackageUploader: No value supplied for SMB_USERNAME, setting default value of:
JamfPackageUploader: No value supplied for SMB_PASSWORD, setting default value of:
JamfPackageUploader: Checking for existing 'Visual Studio Code-1.65.2.pkg' on https://mydomain.jamfcloud.com:8443
JamfPackageUploader: Checking for existing authentication token
JamfPackageUploader: No existing valid token found
JamfPackageUploader: Getting an authentication token
JamfPackageUploader: Existing cookie found: APBALANCEID=aws.usw2-std-parker2-tc-9
JamfPackageUploader: curl command: /usr/bin/curl --silent --show-error -D /tmp/jamf_upload/curl_headers_from_jamf_upload.txt --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt https://mydomain.jamfcloud.com:8443/api/v1/auth/token --request POST --header authorization: Basic redacted --header Content-type: application/json --cookie APBALANCEID=aws.usw2-std-parker2-tc-9
JamfPackageUploader: ERROR: No token received
JamfPackageUploader: No token found, basic auth will be used,
JamfPackageUploader: Existing cookie found: APBALANCEID=aws.usw2-std-parker2-tc-9
JamfPackageUploader: curl command: /usr/bin/curl --silent --show-error -D /tmp/jamf_upload/curl_headers_from_jamf_upload.txt --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt https://mydomain.jamfcloud.com:8443/JSSResource/packages/name/Visual%20Studio%20Code-1.65.2.pkg --request GET --header authorization: Basic redacted --header Accept: application/json --cookie APBALANCEID=aws.usw2-std-parker2-tc-9
JamfPackageUploader: ID: -1
JamfPackageUploader: Existing cookie found: APBALANCEID=aws.usw2-std-parker2-tc-9
JamfPackageUploader: curl command: /usr/bin/curl --silent --show-error -D /tmp/jamf_upload/curl_headers_from_jamf_upload.txt --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt https://mydomain.jamfcloud.com:8443/dbfileupload --request POST --header authorization: Basic redacted --upload-file /Users/autopkg/Library/AutoPkg/Cache/local.pkg.visualstudiocode/Visual Studio Code-1.65.2.pkg --header Accept: application/xml --cookie APBALANCEID=aws.usw2-std-parker2-tc-9 --header DESTINATION: 0 --header OBJECT_ID: -1 --header FILE_TYPE: 0 --header FILE_NAME: Visual Studio Code-1.65.2.pkg --max-time 3600
JamfPackageUploader: HTTP response: 502
JamfPackageUploader: Could not parse XML. Raw output:
JamfPackageUploader: <!DOCTYPE html>
<!--
??????????????MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
I?????????????MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8M
I????????????IMMMM??I????IMMMMMMMMMMNOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOOM
I????????????MMD??????????MMMMMMMMMMNOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOMMM
I????????????MMI??????????MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8OOMMMM
I???????????DMI???????????MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8OOMMMM
I?????????IMMM????????????MMMMMMMMMMMOO8MMMMMM8OOOOOOODMMMMMMMMMOOMMOOOOODMMM8OOOOO8MMMMMMMOOOOOOOOM
M$$$$$$ZNMMMM?????????????MMMMMMMMMMMOO8MMMMMNOOOO8OOOOOOMMMMMMMOOOOOOOOOOOMOOOOOOOOO8MMMMMOOOOOOOOM
MMMMMMMMMMMMNI????????????MMMMMMMMMMMOO8MMMMMMMMMMMMMMDOO8MMMMMMOOOMMMMMMOOOONMMMMMOOOMMMMMMM8OOMMMM
MMMMMMMMMMMMI?????????????MMMMMMMMMMMOO8MMMMMMMMMMMMMMMOOOMMMMMMOONMMMMMMMOODMMMMMMMOONMMMMMM8OOMMMM
MMMMMMMMMMM7??????????????MMMMMMMMMMMOO8MMMMMNOOOOOOOO8OOOMMMMMMOOMMMMMMMMOOMMMMMMMMOODMMMMMM8OOMMMM
MMMMMMMMMOI???????????????MMMMMMMMMMMOO8MMMMOOO8MMMMMMOOOOMMMMMMOOMMMMMMMMOOMMMMMMMMOODMMMMMM8OOMMMM
I?????????????????????????MMMMMMMMMMMOO8MMMNOODMMMMMMMMOOOMMMMMMOOMMMMMMMMOOMMMMMMMMOODMMMMMM8OOMMMM
I?????????????????????????MMMMMMMMMMMOO8MMMNOONMMMMMMMMOOOMMMMMMOOMMMMMMMMOOMMMMMMMMOODMMMMMM8OOMMMM
I?????????????????????????MMMMMMMMMMMOO8MMMMOOONMMMMMM8OOOMMMMMMOOMMMMMMMMOOMMMMMMMMOODMMMMMM8OOMMMM
D????????????III???????II$MMMMMMMMMMMOO8MMMMM88OOOOOOO88OOMMMMMMOOMMMMMMMMOOMMMMMMMMOODMMMMMM8OOMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOMMMMMMMMD888MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOO8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOO8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
-->
<html>
    <head>
        <link rel="icon" sizes="192x192" href='https://www.jamf.com/touch-icon-192x192.png'>
        <link rel="apple-touch-icon-precomposed" sizes="180x180" href='https://www.jamf.com/apple-touch-icon-180x180.png'>
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href='https://www.jamf.com/apple-touch-icon-152x152.png'>
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href='https://www.jamf.com/apple-touch-icon-144x144.png'>
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href='https://www.jamf.com/apple-touch-icon-120x120.png'>
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href='https://www.jamf.com/apple-touch-icon-114x114.png'>
        <link rel="apple-touch-icon-precomposed" sizes="76x76" href='https://www.jamf.com/apple-touch-icon-76x76.png'>
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href='https://www.jamf.com/apple-touch-icon-72x72.png'>
        <link rel="apple-touch-icon-precomposed" href='https://www.jamf.com/apple-touch-icon.png'>
        <link rel="shortcut icon" href='https://www.jamf.com/favicon.ico' type="image/x-icon">
        <link rel="icon" href='https://www.jamf.com/favicon.ico' type="image/x-icon">
        <link rel="mask-icon" href='https://www.jamf.com/pin-mask.svg' color="#5b6983">

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <link rel="stylesheet" type="text/css" href="https://www.jamf.com/jamf-nation/css/jamfnation.min.css"/>

        <title>Jamf Cloud - Timeout</title>
</head>
<body>
    <header class="jamf-nav--fixed headroom headroom--top headroom--not-bottom" data-headroom="" data-offset="70">
        <div class="jamf-nav__bar jamf-nav__bar--global">
            <div class="jamf-nav__bar-content">
                <div class="jamf-nav__links" role="tablist">
                    <a class="jamf-nav__link" href="https://www.jamf.com/" data-analytics-title="Home">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 162 56" class="brand__logo">
                            <title>Jamf</title>
                            <path class="logo__River" fill="#778eb1" d="M33.6,7 C28.1,7 24.8,9.3 23.3,14.3 L19.5,26.2 C18.1,30.1 15.8,31.7 11.7,31.7 L2.2,31.7 C1,31.7 0,32.7 0,33.9 L0,40 C0,41.1 0.9,42 2.1,42 L40.7,42 C41.9,42 42.9,41 42.9,39.8 L42.9,9.1 C42.9,7.9 42,7 40.8,7 L33.6,7 L33.6,7 Z M2.3,0 C1.1,0 0,1.1 0,2.3 L0,18.5 C0,19.8 1,20.8 2.3,20.8 L10.5,20.8 C14.2,20.8 19.4,20 20.8,13.4 C20.8,13.4 22.2,6.7 23,2.8 C23.3,1.3 22.2,-7.10542736e-15 20.7,-7.10542736e-15 L2.3,-7.10542736e-15 L2.3,0 Z"></path>
                            <path class="logo__wordmark" fill="#fff" d="M152.9,13.3 C152.9,7.8 156.6,5.2 161.8,5 L161.8,9.5 L160.9,9.5 C158.6,9.5 157.4,11.4 157.4,13.7 L157.4,17.3 L161.6,17.3 L161.6,21.3 L157.4,21.3 L157.4,43.5 L152.9,43.5 L152.9,21.2 L149,21.2 L149,17.2 L152.9,17.2 L152.9,13.3 L152.9,13.3 Z M137.3,27.7 C137.3,23.2 134.7,21.2 131.6,21.2 C127.9,21.2 125.1,23.6 125.1,27.9 L125.1,43.7 L120.6,43.7 L120.6,27.7 C120.6,23.2 118,21.2 114.9,21.2 C111.2,21.2 108.4,23.6 108.4,27.9 L108.4,43.7 L104,43.7 L104,17.6 L108.5,17.6 L108.5,20.7 L108.6,20.7 C109.8,18 113,17 115.7,17 C118.3,17 121.2,17.7 123.3,21.5 C124.9,18.2 128.3,17 131.7,17 C137.3,17 141.6,20.4 141.6,27.2 L141.6,43.7 L137.1,43.7 L137.1,27.7 L137.3,27.7 Z M83.1,29.9 C77.6,29.9 75.8,32.6 75.8,35.1 C75.8,37.6 77.6,40.3 83.1,40.3 C88.6,40.3 90.4,37.6 90.4,35.1 C90.4,32.6 88.5,29.9 83.1,29.9 L83.1,29.9 L83.1,29.9 Z M90.2,26.2 C90.2,21.9 85.9,20.9 82.5,20.9 C80.1,20.9 77.8,21.5 75.4,22.7 L73.4,19 C77.3,17.3 80.4,17 82.7,17 C88.9,17 94.7,19.7 94.7,25.9 L94.7,43.7 L90.5,43.7 L90.5,40.9 C88.2,43.3 85.7,44.3 82.3,44.3 C76,44.3 71,40.8 71,34.9 C71,30.1 75,25.9 82.2,25.9 C84.9,25.9 87.8,26.7 90.2,28.9 L90.2,26.2 L90.2,26.2 Z M62.5,6 C64.2,6 65.6,7.4 65.6,9.1 C65.6,10.9 64.2,12.3 62.5,12.3 C60.8,12.3 59.4,10.9 59.4,9.2 C59.4,7.4 60.8,6 62.5,6 L62.5,6 L62.5,6 Z M60.4,17.4 L64.9,17.4 L65,46.9 C65,53.7 60.6,56 55.7,56 L54,56 L54,51.8 L55.7,51.8 C60.1,51.8 60.5,49.4 60.5,47.1 L60.4,17.4 L60.4,17.4 Z"></path>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </header>
    <div id="page-content" style="margin-top: 69px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="well">
                        <h2>This Service is Temporarily Unavailable</h2>
                        <p>Please excuse the inconvenience. It appears your request has timed out. Please try again shortly.</p>
                        <p>Please contact us if you need immediate assistance or would like more information.</p>
                    </div>
                    <div class="well">
                        <h4>Technical Support</h4>
                        <p>
                            <p>
                            <span class="col-xs-2">United States</span>
                                <a href="tel:+6122161296">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> (612) 216-1296</a>
                            </p>
                            <p>
                            <span class="col-xs-2">Australia</span>
                                <a href="tel:+610280152224">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> +61 02 80 15 22 24</a>
                            </p>
                            <p>
                            <span class="col-xs-2">Hong Kong</span>
                                <a href="tel:+85258084970">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> +852 5808 4970</a>
                            </p>
                            <p>
                                <span class="col-xs-2">United Kingdom</span>
                                <a href="tel:+442030147479">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> +44 20 30 14 74 79</a>
                            </p>
                            <p>
                                <span class="col-xs-2">France</span>
                                <a href="tel:+33184886656">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> +33 1 84 88 66 56</a>
                            </p>
                            <p>
                                <span class="col-xs-2">Germany</span>
                                <a href="tel:+496996759737">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> +49 69 96 75 97 37</a>
                            </p>
                            <p>
                                <span class="col-xs-2">Netherlands</span>
                                <a href="tel:+31202410671">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> +31 20 241 06 71</a>
                            </p>
                            <p>
                                <span class="col-xs-2">Japan</span>
                                <a href="tel:+81345406654">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> +81 345406654</a>
                            </p>
                            <p>
                                <span class="col-xs-2">China</span>
                                <a href="tel:4008907842">
                                <i class="jcon-answer" role="presentation" aria-hidden="true"></i> 400-890-7842</a>
                            </p>
                            <p>
                                <span class="col-xs-2">Email</span>
                                <a href="mailto:support@jamf.com">
                                <i class="jcon-paper-plane-2" role="presentation" aria-hidden="true"></i> support@jamf.com</a>
                            </p>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Traceback (most recent call last):
  File "/Users/autopkg/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/JamfUploaderProcessors/JamfPackageUploader.py", line 546, in main
    pkg_id = ElementTree.fromstring(r.output).findtext("id")
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 47, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Users/autopkg/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/JamfUploaderProcessors/JamfPackageUploader.py", line 562, in main
    "WARNING: Could not read HTTP response. The package was probably not "
autopkglib.ProcessorError: WARNING: Could not read HTTP response. The package was probably not uploaded successfully
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
WARNING: Could not read HTTP response. The package was probably not uploaded successfully
Failed.
Receipt written to /Users/autopkg/Library/AutoPkg/Cache/local.pkg.visualstudiocode/receipts/visualstudiocode-receipt-20220310-145503.plist

The following recipes failed:
    visualstudiocode.pkg
        Error in local.pkg.visualstudiocode: Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader: Error: WARNING: Could not read HTTP response. The package was probably not uploaded successfully

Nothing downloaded, packaged or imported.
```

Thanks!

**Comment by homebysix** [comment]
I encountered this issue as well:

```
JamfPackageUploader: ERROR: No token received
```

And the subsequent `probably not uploaded` message.

By chance, does the API account you're using have an exclamation mark in the password? Mine did, and when I changed the password to one without an exclamation mark, the issue was resolved.

**Comment by grahampugh** [comment]
Is your Jamf cloud instance really only accessible on port 8443?

**Comment by at-danderson** [comment]
@homebysix that fixed it!  I changed the password to one that did not include a "!" and I have been able to start using the jamf tools.  Thank you!

@grahampugh Yeah, that was an unfortunate byproduct of an on-pre to cloud conversion that could have gone much better.

Thanks again for your help!

**Comment by grahampugh** [comment]
Thanks @homebysix, that's a good tip for the wiki :)

**Comment by grahampugh** [comment]
Now added to the wiki at https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors#jamf-credentials
