### ISSUE TITLE
[Feature Request] Have the JamfPackageUploader processor accept an option to not try to update the package metadata

### ISSUE THREAD

**Issue by Daz-wallace** [grahampugh/jamf-upload#66]
Hi,

As discussed on Slack, would it be possible to add a key to the `JamfPackageUploader` processor to have it skip trying to update the package metadata?

This options requires "update" permissions on packages for the API account, which is...tricky....for us to grant at this time, and not using seems to have no ill benefits for us as for a functionality. 

Thanks!

**Comment by grahampugh** [comment]
Just for visibility here, before looking into the technical side of things, skipping the metadata does have one ill benefit in that without the ability to update the pkg metadata, the SHA512 hash of the package cannot be set. Without this, the Jamf binary will not do a verification on the client that the package is what it says it is. 

So while you do remove the ability for someone obtaining your AutoPkg account credentials to login to Jamf Pro and switch out a package (amongst all the other things it can do like create a policy containing a script that could do whatever they want...), you do expose that slight risk of something on the client itself switching out the package.

**Comment by Daz-wallace** [comment]
There would be a negative security impact from the change, but by making this opt-in I think it'll be ok as the admin's choice.

For us, our API creds used are locked to _only_ allow uploading packages, no existing package modification (so existing packages that are being deployed can't be replaced), and no changes to scripts, policies, groups etc can be made with the same credentials. As for the risk on client, this wouldn't be mitigated but would require local admin rights to execute along with code execution.

**Comment by grahampugh** [comment]
I have added a `skip_metadata_upload` boolean option to `JamfPackageUploader`. I haven't yet pushed this to `autopkg/grahampugh-recipes` because my overnight run is about to start and this will break all my recipes until I upload the trust :-) 

Feel free to copy this processor into your local clone of grahampugh-recipes and give it a go.

**Comment by Daz-wallace** [comment]
Hmm so with the changed option, the package upload seems to hang and timeout. I've pasted the relevant (redacted) output below. 
The package shows in Jamf as "Upload failed"
```JamfPackageUploader: URL for token matches current request
JamfPackageUploader: Existing token is valid
JamfPackageUploader: curl command: /usr/bin/curl --dump-header /tmp/jamf_upload/curl_headers_from_jamf_upload.txt https://[Jamf URL]/api/v1/jamf-pro-version --request GET --silent --show-error --header authorization: Bearer [Bearer token] --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt --header Accept: application/json --cookie-jar /tmp/jamf_upload/curl_cookies_from_jamf_upload.txt --cookie /tmp/jamf_upload/curl_cookies_from_jamf_upload.txt
JamfPackageUploader: Jamf Pro Version: [Jamf Pro Version]
JamfPackageUploader: Token auth will be used, 
JamfPackageUploader: curl command: /usr/bin/curl --dump-header /tmp/jamf_upload/curl_headers_from_jamf_upload.txt https://[Jamf URL].jamfcloud.com/JSSResource/packages/name/Microsoft%20Visual%20Studio%20Code-1.68.1.pkg --request GET --silent --show-error --header authorization: Bearer [Bearer token] --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt --header Accept: application/json --cookie-jar /tmp/jamf_upload/curl_cookies_from_jamf_upload.txt --cookie /tmp/jamf_upload/curl_cookies_from_jamf_upload.txt
JamfPackageUploader: ID: -1
JamfPackageUploader: Package 'Microsoft Visual Studio Code-1.68.1.pkg' not found on server
JamfPackageUploader: curl command: /usr/bin/curl --dump-header /tmp/jamf_upload/curl_headers_from_jamf_upload.txt https://[Jamf URL].jamfcloud.com/dbfileupload --request POST --silent --show-error --header authorization: Basic [Basic Auth token] --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt --output /tmp/jamf_upload/curl_output_from_jamf_upload.txt --upload-file /Users/[Username]/Library/AutoPkg/Cache/local.jamf.10xbanking-VisualStudioCode-pkg-upload/Microsoft Visual Studio Code-1.68.1.pkg --cookie-jar /tmp/jamf_upload/curl_cookies_from_jamf_upload.txt --cookie /tmp/jamf_upload/curl_cookies_from_jamf_upload.txt --header Accept: application/xml --header DESTINATION: 0 --header OBJECT_ID: -1 --header FILE_TYPE: 0 --header FILE_NAME: Microsoft Visual Studio Code-1.68.1.pkg --max-time 3600
curl: (28) Operation timed out after 3599999 milliseconds with 230 out of 230 bytes received
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Users/[Username]/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/JamfUploaderProcessors/JamfPackageUploader.py", line 803, in main
    self.pkg_name, self.pkg_path, self.jamf_url, enc_creds, obj_id
  File "/Users/[Username]/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/JamfUploaderProcessors/JamfPackageUploader.py", line 363, in curl_pkg
    data=pkg_path,
  File "/Users/[Username]/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/JamfUploaderProcessors/JamfUploaderLib/JamfUploaderBase.py", line 371, in curl
    subprocess.check_output(curl_cmd)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--dump-header', '/tmp/jamf_upload/curl_headers_from_jamf_upload.txt', 'https://[Jamf URL].jamfcloud.com/dbfileupload', '--request', 'POST', '--silent', '--show-error', '--header', 'authorization: Basic [Basic Auth token]', '--output', '/tmp/jamf_upload/curl_output_from_jamf_upload.txt', '--output', '/tmp/jamf_upload/curl_output_from_jamf_upload.txt', '--upload-file', '/Users/[Username]/Library/AutoPkg/Cache/local.jamf.10xbanking-VisualStudioCode-pkg-upload/Microsoft Visual Studio Code-1.68.1.pkg', '--cookie-jar', '/tmp/jamf_upload/curl_cookies_from_jamf_upload.txt', '--cookie', '/tmp/jamf_upload/curl_cookies_from_jamf_upload.txt', '--header', 'Accept: application/xml', '--header', 'DESTINATION: 0', '--header', 'OBJECT_ID: -1', '--header', 'FILE_TYPE: 0', '--header', 'FILE_NAME: Microsoft Visual Studio Code-1.68.1.pkg', '--max-time', '3600']' returned non-zero exit status 28.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Command '['/usr/bin/curl', '--dump-header', '/tmp/jamf_upload/curl_headers_from_jamf_upload.txt', 'https://[Jamf URL].jamfcloud.com/dbfileupload', '--request', 'POST', '--silent', '--show-error', '--header', 'authorization: Basic [Basic Auth token]', '--output', '/tmp/jamf_upload/curl_output_from_jamf_upload.txt', '--output', '/tmp/jamf_upload/curl_output_from_jamf_upload.txt', '--upload-file', '/Users/[Username]/Library/AutoPkg/Cache/local.jamf.10xbanking-VisualStudioCode-pkg-upload/Microsoft Visual Studio Code-1.68.1.pkg', '--cookie-jar', '/tmp/jamf_upload/curl_cookies_from_jamf_upload.txt', '--cookie', '/tmp/jamf_upload/curl_cookies_from_jamf_upload.txt', '--header', 'Accept: application/xml', '--header', 'DESTINATION: 0', '--header', 'OBJECT_ID: -1', '--header', 'FILE_TYPE: 0', '--header', 'FILE_NAME: Microsoft Visual Studio Code-1.68.1.pkg', '--max-time', '3600']' returned non-zero exit status 28.
Failed.
Receipt written to /Users/[Username]/Library/AutoPkg/Cache/local.jamf.VisualStudioCode-pkg-upload/receipts/VisualStudioCode-pkg-upload.jamf-receipt-20220623-103335.plist

The following recipes failed:
    /Users/[Username]/Git/it-endpoint-mac-autopkg-overrides/VisualStudioCode-pkg-upload.jamf.recipe
        Error in local.jamf.VisualStudioCode-pkg-upload: Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader: Error: Command '['/usr/bin/curl', '--dump-header', '/tmp/jamf_upload/curl_headers_from_jamf_upload.txt', 'https://[Jamf URL].jamfcloud.com/dbfileupload', '--request', 'POST', '--silent', '--show-error', '--header', 'authorization: Basic [Basic Auth token]', '--output', '/tmp/jamf_upload/curl_output_from_jamf_upload.txt', '--output', '/tmp/jamf_upload/curl_output_from_jamf_upload.txt', '--upload-file', '/Users/[Username]/Library/AutoPkg/Cache/local.jamf.10xbanking-VisualStudioCode-pkg-upload/Microsoft Visual Studio Code-1.68.1.pkg', '--cookie-jar', '/tmp/jamf_upload/curl_cookies_from_jamf_upload.txt', '--cookie', '/tmp/jamf_upload/curl_cookies_from_jamf_upload.txt', '--header', 'Accept: application/xml', '--header', 'DESTINATION: 0', '--header', 'OBJECT_ID: -1', '--header', 'FILE_TYPE: 0', '--header', 'FILE_NAME: Microsoft Visual Studio Code-1.68.1.pkg', '--max-time', '3600']' returned non-zero exit status 28.

The following new items were downloaded:
    Download Path                                                                                                                           
    -------------                                                                                                                           
    /Users/[Username]/Library/AutoPkg/Cache/local.jamf.VisualStudioCode-pkg-upload/downloads/Microsoft Visual Studio Code.zip  

The following packages were built:
    Identifier            Version  Pkg Path                                                                                                                             
    ----------            -------  --------                                                                                                                             
    com.microsoft.VSCode  1.68.1   /Users/[Username]/Library/AutoPkg/Cache/local.jamf.VisualStudioCode-pkg-upload/Microsoft Visual Studio Code-1.68.1.pkg  
``` 

Let me know what else I can do to help :)

**Comment by grahampugh** [comment]
Have you tried that more than once? Did you give it a good couple of minutes after deleting the existing package before trying the upload again (to allow background sync to complete)?

**Comment by Daz-wallace** [comment]
Deleted the package and gave it 15 minutes before running the recipe and got the same issue. Looks like it starts the upload and then just waits the full curl timeout before erroring.
I've reverted the `JamfPackageUploader` process to the pre-changed version and it continues to work as expected

**Comment by grahampugh** [comment]
Hmm that's very odd, I didn't think I had changed that code at all. Gonna have to diff it.

**Comment by grahampugh** [comment]
I'm really struggling to reproduce your curl timeout. In my test it uploads successfully:

```
JamfPackageUploader: Checking for existing package 'DisplayLink_Manager-1.7.0.pkg' on https://jssimporter.jamfcloud.com
JamfPackageUploader: Checking for existing authentication token
JamfPackageUploader: Checking https://jssimporter.jamfcloud.com against https://jssimporter.jamfcloud.com
JamfPackageUploader: URL for token matches current request
JamfPackageUploader: Existing token is valid
JamfPackageUploader: Jamf Pro Version: 10.40.0-b.1.t1655300562
JamfPackageUploader: Token auth will be used, 
JamfPackageUploader: Package 'DisplayLink_Manager-1.7.0.pkg' not found on server
JamfPackageUploader: HTTP response: 200
JamfPackageUploader: Package uploaded successfully, ID=296
JamfPackageUploader: Package 'DisplayLink_Manager-1.7.0.pkg' upload successful
```

Just going to ask - are you sure you copied the processor over correctly? Or is there something else weird on your client preventing network or preventing files getting written anywhere e.g. `/tmp`?

**Comment by Daz-wallace** [comment]
:| 
So I retested today and obviously it worked fine 🤦 
No idea what happened yesterday but it could well be that I carried out a bad copy/paste.
Thank you for all the checks and work on this one!

**Comment by grahampugh** [comment]
That's great. I'll copy it into the main repo in a bit.

**Comment by grahampugh** [comment]
Done.
